# Generated by Django 2.2.16 on 2022-06-13 14:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_auto_20220611_1913'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FollowModel',
            new_name='Follow',
        ),
    ]
